version: '3.8'

# Development overrides
services:
  # Mount source code for hot reload
  caia:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/vendor
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    command: air

  # Use temporal dev server with UI
  temporal:
    ports:
      - "8233:8233" # Temporal UI
    environment:
      - LOG_LEVEL=debug