apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caia-repo-pvc
  namespace: caia-library
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caia-models-pvc
  namespace: caia-library
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard